@startuml UseCases
left to right direction
skinparam packageStyle rectangle

actor "Usuario \n(Biohacker)" as User
actor "Sistema Experto \n(Motor Matemático)" as Engine
actor "Servicios Externos \n(Futuro)" as API

rectangle "Optimizador Cognitivo v8.0" {
  
  package "Fase 1 (Actual)" {
    usecase "Configurar Stack Base" as UC1
    usecase "Activar Tiempos de Cafeína" as UC2
    usecase "Visualizar Proyección de CI" as UC3
    usecase "Recibir Alertas Médicas" as UC4
    usecase "Activar Modo Flow" as UC5
  }

  package "Fase 2 (Próximamente)" {
    usecase "Iniciar Sesión Segura" as UC6
    usecase "Guardar Snapshot Histórico" as UC7
    usecase "Sincronizar Datos de Sueño Real" as UC8
  }
}

' Interacciones del Usuario (Actual)
User --> UC1
User --> UC2
User --> UC5
User --> UC3

' Interacciones del Usuario (Futuro)
User --> UC6
User --> UC7

' Interacciones del Motor
Engine --> UC3 : "Genera Curva"
Engine --> UC4 : "Evalúa Interacciones"
UC1 .> Engine : "Inyecta Datos"
UC2 .> Engine : "Inyecta Datos"

' Interacciones V2
API --> UC8
UC8 .> Engine : "Altera Línea Base"
UC6 .> UC7 : "Requiere"

@enduml
